### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Termik-g** [termux/termux-gui#13]
My phone: realme c21 (rooted). I tried to install from f-droid, but installation failed. I also tried through /system/bin/pm but still no result
![Screenshot_2022-02-28-08-54-36-30_66a3b1c2c181ff92b8bf945e748b6fb7](https://user-images.githubusercontent.com/63584866/155931751-44284348-acb4-4ab9-a788-20a285f6cbd5.jpg)
![Screenshot_2022-02-28-08-53-48-28_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/63584866/155931772-3fa9beb7-d686-4b1f-82a5-6f067db83e09.jpg)

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-gui/issues/4
