### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by mrfoxie** [termux/termux-gui#15]
![Screenshot_20220307-224336_Package installer](https://user-images.githubusercontent.com/25217451/157083944-fcd6e2ed-e770-4796-9346-80a24fbc9948.png)

`Linux localhost 4.19.152-perf-22611703-abM426BXXS3AVA1 #1 SMP PREEMPT Tue Jan 11 14:40:34 KST 2022 aarch64 Android`

**Comment by mrfoxie** [comment]
> Termux-app and all addon apps need to be installed from the same source (so either fdroid only or github releases only)

I have installed all the apps of termux from f-droid and its been installed to latest version but still its gave me that error

**Comment by Grimler91** [comment]
Yeah, the app on fdroid is signed with the wrong key, and fdroid admins have been pretty unresponsive, see https://github.com/termux/termux-gui/issues/4

**Comment by mrfoxie** [comment]
but I had used the app which is released in the GitHub repo [v 0.1.4](https://github.com/termux/termux-gui/releases/tag/0.1.4). It still shows me the same error also not that I have reinstalled all the termux apps from the GitHub repo.

**Comment by mrfoxie** [comment]
> Yeah, the app on fdroid is signed with the wrong key, and fdroid admins have been pretty unresponsive, see #4

![Screenshot_20220529-231854_Package installer](https://user-images.githubusercontent.com/25217451/170884391-f17c443f-468c-44df-a56b-46718313ef3c.png)
i have checked my install app library it's not been install and now it's showing me this error

**Comment by tareksander** [comment]
Did you also install Termux and the other plugins from Github? You can't mix installation sources.

**Comment by mrfoxie** [comment]
no i install termux form f-droid and when I try to install termux gui from f-droid it won't install

**Comment by tareksander** [comment]
You have to install Termux and all plugins from the same source: Github or f-droid. Since Termux:GUI currently doesn't work on f-droid, you have to install everything from Github.

**Comment by mrfoxie** [comment]
ok i will give it a shot
