### ISSUE TITLE
Bluetooth keyboard stops working inside Linux 

### ISSUE THREAD

**Issue by sdanfa** [termux/termux-gui#26]
Hi,
I wake my Bluetooth keyboard after it goes offline automatically. But when it wakes up, I can't type anything in Linux on Termux:GUI app.

**Comment by tareksander** [comment]
Does the keyboard work in other apps when waking up?  

> I can't type anything in Linux on Termux:GUI app.

What do you mean? Termux:GUI has no Linux. Do you mean a program someone created?

**Comment by sdanfa** [comment]
> Does the keyboard work in other apps when waking up?  
> 
> > I can't type anything in Linux on Termux:GUI app.
> 
> What do you mean? Termux:GUI has no Linux. Do you mean a program someone created?

Yes the keyboard works in other apps whne waking up. Just not in Termux:GUI. It works in Termux:GUI when waking up, only if I click Bluetooth button in Android settings to turn it on and off. I'm using Termux:GUI like vnc client for Linux running in Termux. Thanks for your help.

**Comment by tareksander** [comment]
> I'm using Termux:GUI like vnc client for Linux running in Termux.

What program do you use for that? Are you sure you aren't confusing Termux:GUI with Termux:X11?

**Comment by sdanfa** [comment]
> > I'm using Termux:GUI like vnc client for Linux running in Termux.
> 
> What program do you use for that? Are you sure you aren't confusing Termux:GUI with Termux:X11?

Yes, you're right I just checked it's Termux:X11 I have installed.
