### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor"

### ISSUE THREAD

**Issue by MrAdityaAlok** [termux/termux-gui#34]
Android 9 do not have `android.webkit.PacProcessor`

Ref: https://stackoverflow.com/questions/70756680/java-lang-noclassdeffounderror-failed-resolution-of-landroid-webkit-pacprocess

Logs: [Termux_GUI logcat.txt](https://github.com/termux/termux-gui/files/9996954/Termux_GUI.logcat.txt)

**Comment by tareksander** [comment]
Are you using the GitHub Actions build from the latest commit?  
The error occurred when trying to create a WebView?  
From the Stackoverflow question you liked it seems like this is an SDK/framework/Android issue, not an app issue.

**Comment by MrAdityaAlok** [comment]
> Are you using the GitHub Actions build from the latest commit (So I know which version of the code to look at)?

Yes, build from main branch from my fork: https://github.com/MrAdityaAlok/termux-api

I did modify two thing but don't think that would cause this problem.
**If you think my modifications would cause it then inform me, I'll disable that and test again.**
```patch
diff --git a/app/build.gradle b/app/build.gradle
index dbb8478..04dba05 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -25,8 +25,8 @@ android {
         applicationId "com.termux.gui"
         minSdk 24
         targetSdk 31
-        versionCode 7
-        versionName "0.1.6"
+        versionCode 1
+        versionName System.getenv("TERMUX_API_APP_VERSION_NAME")
         externalNativeBuild {
             cmake {
                 arguments ''
@@ -41,6 +41,12 @@ android {
             storePassword 'xrj45yWGLbsO7W0v'
             keyPassword 'xrj45yWGLbsO7W0v'
         }
+        release {
+          storeFile file(System.getenv("KEYSTORE_FILE"))
+          keyAlias System.getenv("KEY_ALIAS")
+          storePassword System.getenv("KEYSTORE_PASS")
+          keyPassword System.getenv("KEYSTORE_PASS")
+        }
     }
     packagingOptions {
         jniLibs {
@@ -48,6 +54,13 @@ android {
         }
     }
 
+    splits {
+        abi{
+            reset ()
+            include 'arm64-v8a'
+            universalApk false
+        }
+    }
 
     buildTypes {
         debug {
@@ -63,7 +76,8 @@ android {
         }
         release {
             minifyEnabled true
-            shrinkResources false
+            shrinkResources true
+            signingConfig signingConfigs.release
             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
         }
     }
@@ -90,15 +104,15 @@ dependencies {
     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
 
     implementation "androidx.security:security-crypto:1.1.0-alpha03"
-    
+
     implementation "com.google.protobuf:protobuf-javalite:3.19.4"
-    
+
     implementation 'androidx.legacy:legacy-support-v4:1.0.0'
     implementation 'com.google.android.material:material:1.6.1'
     implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
     implementation project(path: ':hbuffers')
-    
+
     testImplementation 'junit:junit:4.13.2'
     androidTestImplementation 'androidx.test.ext:junit:1.1.3'
     androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
-}
\ No newline at end of file
+}
diff --git a/app/src/main/java/com/termux/gui/Settings.kt b/app/src/main/java/com/termux/gui/Settings.kt
index 146e7c6..253468b 100644
--- a/app/src/main/java/com/termux/gui/Settings.kt
+++ b/app/src/main/java/com/termux/gui/Settings.kt
@@ -18,7 +18,7 @@ class Settings private constructor() {
         private const val LOGLEVEL_KEY = "loglevel"
         private const val LOGLEVEL_DEFAULT = 0
         private const val JAVASCRIPT_KEY = "javascript"
-        private const val JAVASCRIPT_DEFAULT = false
+        private const val JAVASCRIPT_DEFAULT = true
         val instance = Settings()
     }
     
@@ -74,4 +74,4 @@ class Settings private constructor() {
     
     
     
-}
\ No newline at end of file
+}
```


> The error occurred when trying to create a WebView?

Basically this wasn't error. I tried to run js in webview but it didn't load so I checked logs and thought this might be the problem.

**Comment by MrAdityaAlok** [comment]
`app/src/main/java/com/termux/gui/Settings.kt` modification is because toggle in setting auto resets. I don't know android development much so couldn't fix that.

**Comment by tareksander** [comment]
Can you check if the Android System WebView app is updated on your device (should be on the play store)? Do you use an Android emulator or a physical device?

**Comment by MrAdityaAlok** [comment]
Sorry, for so late reply!

> Can you check if the Android System WebView app is updated on your device (should be on the play store)?

![Screenshot_2022-11-14-20-43-08-148~2](https://user-images.githubusercontent.com/73517616/201696737-8395d640-1fb0-4dee-9197-1f1b0753c271.jpeg)

It got disabled after a playstore update.

> Do you use an Android emulator or a physical device?

Physical device (lenovo tab)

**Comment by MrAdityaAlok** [comment]
> Could you try to install Chrome version 96.0.4664.92 / .104? I got those version numbers from the stackoverflow. If it works with an older Chrome version, then it's a Chrome bug on older Android versions.

Ok there is no warning in older chrome, still javascript do no run. I tried `wv.evaluatejs(alert("hi"))` but nothing happened.
