### ISSUE TITLE
Zoom ImageView

### ISSUE THREAD

**Issue by m00n-err0r** [termux/termux-gui#35]
Hello! How can I zoom in and zoom out image in ImageView? Can you help me, please

**Comment by tareksander** [comment]
You can enable the touch events for the ImageView, track the pointers and their position difference and set the image to a zoomed version accordingly.

**Comment by tareksander** [comment]
If you don't want to scale the image yourself, you could also put the ImageView in a FrameLayout and set the size and position.

**Comment by tareksander** [comment]
> > You can enable the touch events for the ImageView, track the pointers and their position difference and set the image to a zoomed version accordingly.
> 
> It's kinda slow..
> I want something like in regular photo gallery: scaling photos on the fly, more smoothly

You can try my second option. If all else fails you can use a WebView try that.

**Comment by m00n-err0r** [comment]
> 

WebView also does not allow to scale the image. Tried two ways:
With base64 string as src in img tag with setdata:
`with tg.Connection() as c:
    a = tg.Activity(c)
    web = tg.WebView(a)
    web.setdata(f'<img src="data:image/jpeg;base64,{str(img)[2:-1]}" width="100%">')
    input()`
And content uri:
`with tg.Connection() as c:
    a = tg.Activity(c)
    web = tg.WebView(a)
    web.allowcontenturi(True)
    web.loaduri('content://someUri.jpg')
    input()`
In both ways the image was shown, but it was impossible to scale, as when visiting sites

**Comment by tareksander** [comment]
A content URI can only be generated by an Android ContentProvider, I added that option in case you get a raw content URI and have to use it.  
Setdata currently doesn't really work, see [the comment for loadData in WebView](https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)), should be fixed in the next version. For now you should use loadUri with a data URI instead of loadData.

**Comment by m00n-err0r** [comment]
> A content URI can only be generated by an Android ContentProvider, I added that option in case you get a raw content URI and have to use it. Setdata currently doesn't really work, see [the comment for loadData in WebView](https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)), should be fixed in the next version. For now you should use loadUri with a data URI instead of loadData.

I have changed setdata to loaduri and pass in base64 string, but scaling is still unavailable

**Comment by tareksander** [comment]
> > You can enable the touch events for the ImageView, track the pointers and their position difference and set the image to a zoomed version accordingly.
> 
> It's kinda slow.. I want something like in regular photo gallery: scaling photos on the fly, more smoothly

If you want faster image display you can use a [shared buffer](https://github.com/tareksander/termux-gui-python-bindings/blob/main/TUTORIAL.md#buffers). Also scale the image as a bitmap. That way you don't need encode and decode the image as much.
