### ISSUE TITLE
conflicting names with termux app

### ISSUE THREAD

**Issue by wong-fi-hung** [termux/termux-gui#39]
i'am trying to install Termux:GUI on redmi 4x with installed termux app, but cannot to install.
the install will work if remove termux app first and then install gui termux, and ther install termux again, and the installation process work fine.
i think this a bad idea, because the termux:GUI app making me to work hard only for succes install lol.
Package Manager Log: unable to install, app with some name has already installed.
image screenshot :  
![termux-gui-err](https://user-images.githubusercontent.com/68433096/215415511-2124be35-dca5-423f-a187-4b1a2375b40a.png)
↓↓↓↓

**Comment by xalexalex** [comment]
It's not a matter of name: the apps must have been built by the same person. You cannot install termux:app from the play store and termux:gui from f-droid, for example, or one from f-droid and the other built by you. Is that the case?

**Comment by wong-fi-hung** [comment]
> It's not a matter of name: the apps must have been built by the same person. You cannot install termux:app from the play store and termux:gui from f-droid, for example, or one from f-droid and the other built by you. Is that the case?

no, i has install from available release pages. D

**Comment by tareksander** [comment]
> no, i has install from available release pages. D

Also the Termux app, not just Termux:GUI? Do other Termux plugins work?

**Comment by wong-fi-hung** [comment]
> > no, i has install from available release pages. D
> 
> Also the Termux app, not just Termux:GUI? Do other Termux plugins work?

the other plugins like termux:boot, termux:styling, termux:tasker, termux:api, termux:X11, termux:widget is working properly with out any problems.
wherever the termux  app is come from.

**Comment by tareksander** [comment]
Termux and all plugins have to come from the same source: https://github.com/termux/termux-app#installation

**Comment by wong-fi-hung** [comment]
fixed...
