### ISSUE TITLE
[question]editText view multiple roles issue

### ISSUE THREAD

**Issue by GTMssj** [termux/termux-gui#43]
I'm currently working on a project where I need to input multiple lines of words in editText view, but I can't seem to find the correct args or method for these 2 functions:

1. wrap around the words(switch to another line when the input reaches the limit);

2. input multiple lines(when I hit enter, cursor moves to next line of words)

help plz

**Comment by tareksander** [comment]
Have you tried the type `textMultiLine` for createEditText?

**Comment by GTMssj** [comment]
> Have you tried the type `textMultiLine` for createEditText?

nope, what should I do to implement this textMultiLine?

**Comment by GTMssj** [comment]
> > Have you tried the type `textMultiLine` for createEditText?
> 
> nope, what should I do to implement this textMultiLine?

oh, I found it in inputtype, thanks for the reminder!
