### ISSUE TITLE
Provide instructions for root-forced installation to overcome the f-droid signing problem

### ISSUE THREAD

**Issue by compilebunny** [termux/termux-gui#45]
/This looks like a great framework for development of miniapps that rely on both Termux and the standard Android gui hooks. Unfortunately, it is being held back by the lack of an f-droid signed package to provide support for sharedUID.

The solution proposed in the readme is to uninstall F-droid Termux and install the Github version. However, this results in the user losing updates; most people won't go back to Github for updates and will end up with an out of date, insecure Termux on their system after a while. Its also a giant pain in the butt.

Can I request that you provide instructions for installing the APK as root and bypassing the signature check? An alternative would be to identify the files from the APK that can be placed (as root) in /data/data/ manually and their user changed.

There are apps such as LuckyPatcher which promise to do this, but they add an extra layer of complexity and potential security issues.

**Comment by twaik** [comment]
There is no way to bypass signature checks. Even with root permissions. The only thing you can do is to backup termux and restore it after reinstalling from github.

**Comment by compilebunny** [comment]
> There actually is a way to bypass security check but it involves patching of Android framework to force disable (say break) the signature checking. This can be done by either LuckyPatcher like you mentioned, installing a zip package through recovery, using Xposed module or manually patching Android jar files. All such methods can be found on https://xdaforums.com/
> 
> If you are looking for methods which don't compromise security, they do not exist.
> 
> If you place APK file to /data, it would be verified and installed on the next boot. Verification performed on every boot, so the app will be force disabled from use if verification failed.

Yeah, I'm hoping to avoid those methods if possible. Xposed is probably the least risky of them, but its compatibility status is always changing. 

Guided placement of the files in /data and then changing the uid/gid is the approach that was taken to resolving this sort of problem for updates with different signatures, at least with older versions of Android. I haven't kept up with how things have changed, and have only seen it work with updates, not with sharedUID.
