### ISSUE TITLE
Function request: clearFocus

### ISSUE THREAD

**Issue by mumumusuc** [termux/termux-gui#52]
I notice that there is no function to clear view's focus(please correct me if i am wrong), so I run into a problem :

1. create an `Activity` with `interceptBackButton=true` and receive it's `BackButtonEvent`;
2. create a single `SurfaceView` with `keyboard=true`;
3. request `SufaceView`'s focus and the soft keyboard shows;
4. use back key or `Activity`'s `HideSoftKeyboardRequest` to hide the soft keyboard;
 
as a result, I still receive keyevent with code 4(go back) instead of `BackButtonEvent` when pressing the back key. So maybe a function like `clearFocus` or `hideSoftInputFromWindow` is needed to stop view's keyevent I think.

https://github.com/termux/termux-gui/assets/6997430/5e5611ba-f946-4c16-b72c-17f8623ccdb8

**Comment by tareksander** [comment]
Sorry, it seems the hardware keyboard focus (to which the back button belongs it seems) can't really be reset. You'll have to translate the back button key events to BackButtonEvents yourself on the client. And from my quick test, it seems the volume keys are also consumed by the SurfaceView.

**Comment by mumumusuc** [comment]
Thanks for the reply, I will give it a try.
