### ISSUE TITLE
Request: more detailed KeyEvent

### ISSUE THREAD

**Issue by mumumusuc** [termux/termux-gui#53]
Currently `Termux:GUI` sends the same `KeyEvent` either on `ACTION_DOWN` or `ACTION_UP`, I'd like to be able to get more detailed `KeyEvent` to differentiate between them, and it would be nice to have `RepeatCount` and `FLAG` field, thank you.

**Comment by tareksander** [comment]
Implemented and pushed it, but haven't tested yet. The C library now has `event.key.flags` and `event.key.down`. `RepeatCount` can be implemented yourself if needed, just count the number of down events for a key.

**Comment by mumumusuc** [comment]
> Implemented and pushed it, but haven't tested yet. The C library now has `event.key.flags` and `event.key.down`. `RepeatCount` can be implemented yourself if needed, just count the number of down events for a key.

`Termux:GUI` works fine, I received these new fields, but I don't test the C library.

BTW, enum `KeyCode` and `KeyFlag` is defined in proto but not used, maybe it's a bug?

**Comment by tareksander** [comment]
How are you using the plugin then? Do you read and write the protobuf messages yourself?

**Comment by mumumusuc** [comment]
> How are you using the plugin then? Do you read and write the protobuf messages yourself?

Yes, I implement the proto with rust by myself because I need it to be fast and async

**Comment by tareksander** [comment]
Nice coincidence, I'm working on an official Rust library. It's going to be sync though, I have no experience with async Rust.
