### ISSUE TITLE
Hardware Buffer alpha channel

### ISSUE THREAD

**Issue by lualvsil** [termux/termux-gui#57]
In hardware buffer, alpha channel is ignored, even creating with RGBA8888 format.

**Comment by tareksander** [comment]
It's not ignored per se, it's just that no alpha blending is done with the SurfaceView for better performance. For what do you need alpha?

**Comment by lualvsil** [comment]
> It's not ignored per se, it's just that no alpha blending is done with the SurfaceView for better performance. For what do you need alpha?

I managed to solve it using 

glEnable(GL_BLEND); glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
