### ISSUE TITLE
Are there plans for GLESv3 support?

### ISSUE THREAD

**Issue by Fancy2209** [termux/termux-gui#62]
I was looking for ways to get FNA on Android and one of the ideas I remembered was using Termux:GUI since it's known to work with SDL wich is what FNA is mainly built around, but it only supportes GLESv3, not v2, so I am curious, are there any plans for ESv3 or Vulkan at some point?

**Comment by tareksander** [comment]
All GLES versions that are supported by the hardware are supported, the same with Vulkan. The only requirements are the extensions to import HardwareBuffers into EGL images or Vulkan memory objects.

**Comment by Fancy2209** [comment]
> All GLES versions that are supported by the hardware are supported, the same with Vulkan. The only requirements are the extensions to import HardwareBuffers into EGL images or Vulkan memory objects.

Ahhh I see 
Only GLESv2 being mentioned got me confused, my bad
